[tool.ruff]
line-length = 119
indent-width = 4
target-version = "py39"

[tool.ruff.lint]
# See Rules in Ruff documentation: https://docs.astral.sh/ruff/rules/
select = [
    "B",   # bugbear
    "DJ",  # flake8-django
    "E",   # pycodestyle errors
    "F",   # pyflakes
    "I",   # isort
    "INP", # flake8-tidy-imports
    "UP",  # pyupgrade
    "W",   # pycodestyle warnings
]

[tool.ruff.lint.isort]
combine-as-imports = true
default-section = "first-party"
known-third-party = [
    "asgiref",
    "django",
]

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["INP001"] # Scripts are not part of the package.